### PR TITLE
Feature/hounslow ch301 add custom eligibility type fields to services

### PR DESCRIPTION
**Pull request by fred-aghq**
…ty fields

https://app.clubhouse.io/ayup-digital-ltd/story/301/add-custom-eligibility-type-fields-to-services-table

### Development checklist

- [ ] Changes have been made to the API?
  - [ ] If so, the OpenAPI specification has been updated
- [x] Database migrations have been added?
  - [x] If so, the MySQL Workbench ERD has been updated
- [x] The code has been linted `./develop composer fix:style`

### CODE REVIEW

**Review by appsol — APPROVED** [review]
All good.

**Review by appsol — CHANGES_REQUESTED** [review]
Add to migration such that all current relationships copy the data into the new custom fields

**Comment by fred-aghq** [comment]
> Should the migration not also move existing data, i.e. from the service_criteria table into these new custom fields? That way all existing service criteria data is preserved.

I asked @AyupMike  about this and he said no, IIRC. I agree though - I thought we'd at least have referential integrity but there is a ticket that requires service_criteria table to be dropped

**Review by appsol — APPROVED** [review]
I admit I'm slightly confused about some of the approaches in the service eligibility feature.
That said if it has been approved that we do not need to migrate the existing data then I'm happy to approve this PR.

**Pull request merged**
